nelmio_cors:
    defaults:
        # allow_credentials: true
        origin_regex: false
        allow_origin: ["%env(CORS_ALLOW_ORIGIN)%"]
        allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
        # allow_headers: ["Content-Type", "Authorization", "Accept"]
        allow_headers: ["Content-Type", "Authorization"]
        expose_headers: ["Link"]
        max_age: 3600
    paths:
        "^/": null
