framework:
    rate_limiter:
        api:
            policy: "sliding_window"
            limit: 1000
            interval: "5 minutes"

        login:
            policy: "sliding_window"
            limit: 3
            interval: "1 minute"
